
package soap.cod;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyCodSoapService", targetNamespace = "http://cod.soap/", wsdlLocation = "http://127.0.0.1:8080/apps/cod/?wsdl")
public class MyCodSoapService
    extends Service
{

    private final static URL MYCODSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYCODSOAPSERVICE_EXCEPTION;
    private final static QName MYCODSOAPSERVICE_QNAME = new QName("http://cod.soap/", "MyCodSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/apps/cod/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYCODSOAPSERVICE_WSDL_LOCATION = url;
        MYCODSOAPSERVICE_EXCEPTION = e;
    }

    public MyCodSoapService() {
        super(__getWsdlLocation(), MYCODSOAPSERVICE_QNAME);
    }

    public MyCodSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYCODSOAPSERVICE_QNAME, features);
    }

    public MyCodSoapService(URL wsdlLocation) {
        super(wsdlLocation, MYCODSOAPSERVICE_QNAME);
    }

    public MyCodSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYCODSOAPSERVICE_QNAME, features);
    }

    public MyCodSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyCodSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CodSoap
     */
    @WebEndpoint(name = "MyCodSoapPort")
    public CodSoap getMyCodSoapPort() {
        return super.getPort(new QName("http://cod.soap/", "MyCodSoapPort"), CodSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CodSoap
     */
    @WebEndpoint(name = "MyCodSoapPort")
    public CodSoap getMyCodSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cod.soap/", "MyCodSoapPort"), CodSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYCODSOAPSERVICE_EXCEPTION!= null) {
            throw MYCODSOAPSERVICE_EXCEPTION;
        }
        return MYCODSOAPSERVICE_WSDL_LOCATION;
    }

}
