
package soap.cod;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CodSoap", targetNamespace = "http://cod.soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CodSoap {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns soap.cod.StandardResult
     */
    @WebMethod(operationName = "Register")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Register", targetNamespace = "http://cod.soap/", className = "soap.cod.Register")
    @ResponseWrapper(localName = "RegisterResponse", targetNamespace = "http://cod.soap/", className = "soap.cod.RegisterResponse")
    @Action(input = "http://cod.soap/CodSoap/RegisterRequest", output = "http://cod.soap/CodSoap/RegisterResponse")
    public StandardResult register(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns soap.cod.StandardResult
     */
    @WebMethod(operationName = "Login")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Login", targetNamespace = "http://cod.soap/", className = "soap.cod.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://cod.soap/", className = "soap.cod.LoginResponse")
    @Action(input = "http://cod.soap/CodSoap/LoginRequest", output = "http://cod.soap/CodSoap/LoginResponse")
    public StandardResult login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "RollDice")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RollDice", targetNamespace = "http://cod.soap/", className = "soap.cod.RollDice")
    @ResponseWrapper(localName = "RollDiceResponse", targetNamespace = "http://cod.soap/", className = "soap.cod.RollDiceResponse")
    @Action(input = "http://cod.soap/CodSoap/RollDiceRequest", output = "http://cod.soap/CodSoap/RollDiceResponse")
    public Boolean rollDice(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<soap.cod.ScoreBoardResult>
     */
    @WebMethod(operationName = "GetScoreBoard")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetScoreBoard", targetNamespace = "http://cod.soap/", className = "soap.cod.GetScoreBoard")
    @ResponseWrapper(localName = "GetScoreBoardResponse", targetNamespace = "http://cod.soap/", className = "soap.cod.GetScoreBoardResponse")
    @Action(input = "http://cod.soap/CodSoap/GetScoreBoardRequest", output = "http://cod.soap/CodSoap/GetScoreBoardResponse")
    public List<ScoreBoardResult> getScoreBoard();

}
